
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf7\xa7u(X\x13\x90F\x97\xc8\x19I\x9d\xe6\xf2:'
    
_lr_action_items = {'COMMENT':([0,1,2,4,5,8,11,13,14,15,16,19,20,21,22,23,],[2,-7,-9,9,2,-10,-8,-11,-16,18,2,-14,-17,-12,2,-15,]),'INFOLINE':([0,1,2,5,8,11,],[4,-7,-9,4,-10,-8,]),'NEWLINE':([2,4,9,14,15,18,20,],[8,10,17,-16,19,23,-17,]),'NUMBER':([6,10,13,14,15,16,17,19,20,21,23,],[14,-5,-11,-16,20,14,-6,-14,-17,-12,-15,]),'$end':([1,2,3,7,8,11,12,13,14,15,16,19,20,21,22,23,],[-7,-9,-1,0,-10,-8,-2,-11,-16,-13,-3,-14,-17,-12,-4,-15,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comment':([0,5,16,22,],[1,11,1,11,]),'data_line':([6,16,],[13,21,]),'touchstone1':([0,5,],[3,12,]),'comments':([0,16,],[5,22,]),'infoline':([0,5,],[6,6,]),'data_lines':([6,],[16,]),'numbers':([6,16,],[15,15,]),'touchstone':([0,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> touchstone","S'",1,None,None,None),
  ('touchstone -> touchstone1','touchstone',1,'p_touchstone','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',52),
  ('touchstone -> comments touchstone1','touchstone',2,'p_touchstone','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',53),
  ('touchstone1 -> infoline data_lines','touchstone1',2,'p_touchstone1','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',62),
  ('touchstone1 -> infoline data_lines comments','touchstone1',3,'p_touchstone1','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',63),
  ('infoline -> INFOLINE NEWLINE','infoline',2,'p_infoline','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',69),
  ('infoline -> INFOLINE COMMENT NEWLINE','infoline',3,'p_infoline','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',70),
  ('comments -> comment','comments',1,'p_comments','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',76),
  ('comments -> comments comment','comments',2,'p_comments','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',77),
  ('comment -> COMMENT','comment',1,'p_comment','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',85),
  ('comment -> COMMENT NEWLINE','comment',2,'p_comment','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',86),
  ('data_lines -> data_line','data_lines',1,'p_data_lines','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',91),
  ('data_lines -> data_lines data_line','data_lines',2,'p_data_lines','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',92),
  ('data_line -> numbers','data_line',1,'p_data_line','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',102),
  ('data_line -> numbers NEWLINE','data_line',2,'p_data_line','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',103),
  ('data_line -> numbers COMMENT NEWLINE','data_line',3,'p_data_line','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',104),
  ('numbers -> NUMBER','numbers',1,'p_numbers','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',110),
  ('numbers -> numbers NUMBER','numbers',2,'p_numbers','C:\\python27\\external\\hftools\\hftools\\io\\lexing.py',111),
]
